#!/usr/bin/sh

# HiDPI computers
HiDPIComputers=("Blade-Stealth")

# Export variables
NORD0='#2e3440'
NORD1='#3b4252'
NORD2='#434c5e'
NORD3='#4c566a'
NORD4='#d8dee9'
NORD5='#e5e9f0'
NORD6='#eceff4'
NORD7='#8fbcbb'
NORD8='#88c0d0'
NORD9='#81a1c1'
NORD10='#5e81ac'
NORD11='#bf616a'
NORD12='#d08770'
NORD13='#ebcb8b'
NORD14='#a3be8c'
NORD15='#b48ead'

sxhkd &
xcompmgr &

feh --bg-fill $HOME/Wallpaper.* --no-fehbg &

$HOME/.config/polybar/launch.sh

for monitor in $(bspc query -M --names)
do
  bspc monitor $monitor -d TERM WWW DEV PLAY VIRT OTHERS
done


bspc config border_width         2
bspc config window_gap           10
bspc config top_padding          17 # height of polybar

for com in "${HiDPIComputers[@]}";
do
  if [ "$com" = "$(hostname)" ];
  then
    bspc config border_width         4
    bspc config window_gap           20
    bspc config top_padding          34 # height of polybar
  fi
done

bspc config active_border_color $NORD3
bspc config focused_border_color $NORD9
bspc config presel_feedback_color $NORD9
bspc config normal_border_color $NORD0

bspc config split_ratio                  0.5

bspc config borderless_monocle          true
bspc config gapless_monocle             true

bspc config remove_unplugged_monitors   true

# For Reference, do it later.
# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
